export type Product = {
  id: string
  name: string
  description: string
  price: number
  image: string
  category: "supplements" | "equipment" | "food-drinks"
  subcategory?: "healthy-meals" | "protein-bars" | "energy-drinks"
  stripePriceId: string
}

export type GroupActivity = {
  id: string
  name: string
  description: string
  image: string
  duration: string
  capacity: number
  instructor: string
}

export const PRODUCTS: Product[] = [
  // Supplements
  {
    id: "sup-1",
    name: "Whey Protein Isolate",
    description:
      "Pure whey protein isolate with 25g protein per serving. Fast-absorbing, low carb formula perfect for post-workout recovery.",
    price: 49.99,
    image: "/whey-protein-powder.jpg",
    category: "supplements",
    stripePriceId: "price_sup_1",
  },
  {
    id: "sup-2",
    name: "Creatine Monohydrate",
    description: "Micronized creatine monohydrate for increased strength and muscle mass. 300 servings per container.",
    price: 24.99,
    image: "/creatine-powder.png",
    category: "supplements",
    stripePriceId: "price_sup_2",
  },
  {
    id: "sup-3",
    name: "BCAA Complex",
    description:
      "Branched-chain amino acids in optimal 2:1:1 ratio. Supports muscle recovery and reduces fatigue during intense training.",
    price: 34.99,
    image: "/bcaa-supplement.jpg",
    category: "supplements",
    stripePriceId: "price_sup_3",
  },
  {
    id: "sup-4",
    name: "Pre-Workout Energy",
    description:
      "High-energy pre-workout formula with caffeine and beta-alanine for explosive workouts and improved endurance.",
    price: 39.99,
    image: "/pre-workout-supplement.jpg",
    category: "supplements",
    stripePriceId: "price_sup_4",
  },
  {
    id: "sup-5",
    name: "Multivitamin Complex",
    description: "Complete daily multivitamin with minerals and antioxidants. Supports overall health and recovery.",
    price: 29.99,
    image: "/multivitamin-pills.png",
    category: "supplements",
    stripePriceId: "price_sup_5",
  },
  {
    id: "sup-6",
    name: "Omega-3 Fish Oil",
    description: "Pure fish oil with 1000mg omega-3 per serving. Supports heart health and joint recovery.",
    price: 19.99,
    image: "/fish-oil-supplement.jpg",
    category: "supplements",
    stripePriceId: "price_sup_6",
  },
  {
    id: "sup-7",
    name: "ZMA Complex",
    description: "Zinc, magnesium, and B6 formula for improved sleep quality and muscle recovery.",
    price: 27.99,
    image: "/zma-supplement.jpg",
    category: "supplements",
    stripePriceId: "price_sup_7",
  },
  {
    id: "sup-8",
    name: "Casein Protein Powder",
    description:
      "Slow-release casein protein for sustained amino acid delivery. Perfect for nighttime or meal replacement.",
    price: 44.99,
    image: "/casein-protein.jpg",
    category: "supplements",
    stripePriceId: "price_sup_8",
  },

  // Equipment (renamed from gym-products)
  {
    id: "gym-1",
    name: "Adjustable Dumbbell Set",
    description: "5-50 lb adjustable dumbbells with storage stand. Perfect for home or commercial gyms.",
    price: 299.99,
    image: "/adjustable-dumbbells.jpg",
    category: "equipment",
    stripePriceId: "price_gym_1",
  },
  {
    id: "gym-2",
    name: "Resistance Band Set",
    description: "Set of 5 heavy-duty resistance bands with carry case. Color-coded for different resistance levels.",
    price: 34.99,
    image: "/resistance-bands-exercise.png",
    category: "equipment",
    stripePriceId: "price_gym_2",
  },
  {
    id: "gym-3",
    name: "Yoga Mat Premium",
    description: "Non-slip yoga mat with carrying strap. Thick, durable foam for maximum comfort and stability.",
    price: 39.99,
    image: "/rolled-yoga-mat.png",
    category: "equipment",
    stripePriceId: "price_gym_3",
  },
  {
    id: "gym-4",
    name: "Jump Rope Speed",
    description: "Professional-grade speed jump rope with adjustable length. Ideal for cardio and conditioning.",
    price: 24.99,
    image: "/jump-rope.jpg",
    category: "equipment",
    stripePriceId: "price_gym_4",
  },
  {
    id: "gym-5",
    name: "Foam Roller Muscle",
    description: "High-density foam roller for muscle recovery and myofascial release. 36 inches long.",
    price: 29.99,
    image: "/foam-roller.jpg",
    category: "equipment",
    stripePriceId: "price_gym_5",
  },
  {
    id: "gym-6",
    name: "Pull-Up Bar Doorway",
    description: "Heavy-duty pull-up bar fits most door frames. Maximum weight capacity: 300 lbs.",
    price: 49.99,
    image: "/pull-up-bar.jpg",
    category: "equipment",
    stripePriceId: "price_gym_6",
  },
  {
    id: "gym-7",
    name: "Kettlebell Iron",
    description: "Cast iron kettlebell available in 10-50 lb weights. Versatile for strength and conditioning.",
    price: 44.99,
    image: "/kettlebell.jpg",
    category: "equipment",
    stripePriceId: "price_gym_7",
  },
  {
    id: "gym-8",
    name: "Ab Roller Wheel",
    description: "Dual-wheel ab roller with knee pad. Strengthens core and abdominal muscles effectively.",
    price: 19.99,
    image: "/ab-roller.jpg",
    category: "equipment",
    stripePriceId: "price_gym_8",
  },

  // Food & Drinks - Healthy Meals
  {
    id: "fd-1",
    name: "Grilled Chicken Meal Prep",
    description: "Lean grilled chicken breast with brown rice and steamed broccoli. High protein, low fat.",
    price: 12.99,
    image: "/chicken-meal-prep.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_1",
  },
  {
    id: "fd-2",
    name: "Salmon Protein Bowl",
    description: "Wild-caught salmon with quinoa, sweet potato, and vegetables. Omega-3 rich.",
    price: 14.99,
    image: "/salmon-bowl.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_2",
  },
  {
    id: "fd-3",
    name: "Turkey & Veggie Wrap",
    description: "Lean ground turkey with whole wheat wrap, mixed vegetables, and hummus.",
    price: 9.99,
    image: "/turkey-wrap.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_3",
  },
  {
    id: "fd-4",
    name: "Egg White Omelet",
    description: "3 whole eggs with spinach, mushrooms, and low-fat cheese. Perfect pre-workout meal.",
    price: 8.99,
    image: "/egg-omelet.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_4",
  },
  {
    id: "fd-5",
    name: "Tuna Salad Power Bowl",
    description: "Fresh tuna, mixed greens, avocado, and olive oil dressing. 30g protein per serving.",
    price: 11.99,
    image: "/tuna-salad.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_5",
  },
  {
    id: "fd-6",
    name: "Lean Beef Stir-Fry",
    description: "Grass-fed lean beef with broccoli, bell peppers, and brown rice. Rich in iron.",
    price: 13.99,
    image: "/beef-stir-fry.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_6",
  },
  {
    id: "fd-7",
    name: "Baked Cod with Veggies",
    description: "Wild-caught cod with roasted vegetables and sweet potato. Low calorie, high protein.",
    price: 12.49,
    image: "/baked-cod.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_7",
  },
  {
    id: "fd-8",
    name: "Chickpea Buddha Bowl",
    description: "Plant-based bowl with chickpeas, quinoa, kale, and tahini dressing. Vegan protein.",
    price: 10.99,
    image: "/buddha-bowl.jpg",
    category: "food-drinks",
    subcategory: "healthy-meals",
    stripePriceId: "price_fd_8",
  },

  // Food & Drinks - Protein Bars
  {
    id: "fd-9",
    name: "Whey Protein Bar",
    description: "High-protein bar with 20g whey protein, low sugar. Chocolate flavor.",
    price: 2.49,
    image: "/protein-bar-chocolate.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_9",
  },
  {
    id: "fd-10",
    name: "Almond Butter Protein Bar",
    description: "Creamy almond butter filling with 18g protein. Gluten-free and no artificial sweeteners.",
    price: 2.99,
    image: "/almond-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_10",
  },
  {
    id: "fd-11",
    name: "Peanut Butter Crunch Bar",
    description: "Peanut butter with crispy granola bits. 17g protein per bar.",
    price: 2.49,
    image: "/peanut-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_11",
  },
  {
    id: "fd-12",
    name: "Dark Chocolate & Coconut Bar",
    description: "Dark chocolate coating with coconut filling. 19g protein, 150 calories.",
    price: 2.79,
    image: "/chocolate-coconut-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_12",
  },
  {
    id: "fd-13",
    name: "Vanilla Wafer Protein Bar",
    description: "Vanilla flavored bar with 20g protein. High fiber, low carb.",
    price: 2.49,
    image: "/vanilla-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_13",
  },
  {
    id: "fd-14",
    name: "Strawberry Shortcake Bar",
    description: "Strawberry flavored bar with 18g protein. Tastes like dessert!",
    price: 2.69,
    image: "/strawberry-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_14",
  },
  {
    id: "fd-15",
    name: "Cookie Dough Protein Bar",
    description: "Cookie dough bites in a chocolate coating. 19g protein per bar.",
    price: 2.89,
    image: "/cookie-dough-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_15",
  },
  {
    id: "fd-16",
    name: "Caramel Nut Protein Bar",
    description: "Caramel with almonds and cashews. 17g protein, 200 calories.",
    price: 2.79,
    image: "/caramel-bar.jpg",
    category: "food-drinks",
    subcategory: "protein-bars",
    stripePriceId: "price_fd_16",
  },

  // Food & Drinks - Energy Drinks
  {
    id: "fd-17",
    name: "Tropical Thunder Energy",
    description: "Tropical mango and passion fruit flavor. 200mg caffeine, B-vitamins.",
    price: 3.49,
    image: "/tropical-energy.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_17",
  },
  {
    id: "fd-18",
    name: "Lightning Bolt Citrus",
    description: "Lemon and lime energy drink. 150mg caffeine, sugar-free.",
    price: 3.29,
    image: "/citrus-energy.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_18",
  },
  {
    id: "fd-19",
    name: "Berry Blast Power Drink",
    description: "Mixed berry flavor with antioxidants. 180mg caffeine, electrolytes.",
    price: 3.59,
    image: "/berry-energy.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_19",
  },
  {
    id: "fd-20",
    name: "Glacier Mint Energy",
    description: "Crisp mint flavor with cooling effect. 160mg caffeine, performance blend.",
    price: 3.49,
    image: "/mint-energy.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_20",
  },
  {
    id: "fd-21",
    name: "Rocket Fuel Pre-Workout Drink",
    description: "Intense grape flavor with creatine and taurine. 220mg caffeine.",
    price: 3.99,
    image: "/grape-fuel.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_21",
  },
  {
    id: "fd-22",
    name: "Hydro Wave Electrolyte",
    description: "Orange flavored hydration drink. 100mg caffeine, 5 electrolytes.",
    price: 3.29,
    image: "/orange-hydro.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_22",
  },
  {
    id: "fd-23",
    name: "Neon Surge Energy",
    description: "Watermelon flavor with BCAAs and beta-alanine. 190mg caffeine.",
    price: 3.69,
    image: "/watermelon-surge.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_23",
  },
  {
    id: "fd-24",
    name: "Peach Paradise Energy",
    description: "Smooth peach flavor with amino acids. 170mg caffeine, natural ingredients.",
    price: 3.49,
    image: "/peach-energy.jpg",
    category: "food-drinks",
    subcategory: "energy-drinks",
    stripePriceId: "price_fd_24",
  },
]

export const CATEGORIES = [
  { id: "supplements", name: "Supplements", description: "Premium nutritional supplements" },
  { id: "equipment", name: "Equipment", description: "Gym equipment and accessories" },
  { id: "food-drinks", name: "Food & Drinks", description: "Healthy meals, bars, and drinks" },
] as const

export const GROUP_ACTIVITIES: GroupActivity[] = [
  {
    id: "yoga-class",
    name: "Yoga Classes",
    description: "Flexibility, balance, and mindfulness training with certified instructors",
    image: "/diverse-yoga-class.png",
    duration: "60 min",
    capacity: 20,
    instructor: "Sarah Johnson",
  },
  {
    id: "hiit-training",
    name: "HIIT Training",
    description: "High-intensity interval training for maximum calorie burn",
    image: "/hiit-class.png",
    duration: "45 min",
    capacity: 15,
    instructor: "Mike Rodriguez",
  },
  {
    id: "spin-class",
    name: "Spin Class",
    description: "Indoor cycling classes to build endurance and leg strength",
    image: "/spin-class.png",
    duration: "50 min",
    capacity: 25,
    instructor: "Emily Chen",
  },
  {
    id: "personal-training",
    name: "Personal Training",
    description: "One-on-one sessions with certified trainers and customized workout plans",
    image: "/personal-training-session.png",
    duration: "60 min",
    capacity: 1,
    instructor: "Various Trainers",
  },
  {
    id: "crossfit",
    name: "CrossFit Fundamentals",
    description: "Learn proper form and technique for functional fitness movements",
    image: "/crossfit-class.jpg",
    duration: "60 min",
    capacity: 12,
    instructor: "Jake Thompson",
  },
  {
    id: "boxing-cardio",
    name: "Boxing Cardio",
    description: "Combine cardio with boxing technique for total body workout",
    image: "/boxing-class.jpg",
    duration: "50 min",
    capacity: 18,
    instructor: "Alex Martinez",
  },
  {
    id: "pilates",
    name: "Pilates Core Strength",
    description: "Focus on core strengthening and flexibility improvement",
    image: "/pilates-class.png",
    duration: "55 min",
    capacity: 15,
    instructor: "Lisa Anderson",
  },
  {
    id: "nutrition-coaching",
    name: "Nutrition Coaching",
    description: "Personalized nutrition coaching with meal planning and dietary guidance",
    image: "/nutrition-coaching.png",
    duration: "30 min",
    capacity: 1,
    instructor: "Dr. Rachel Green",
  },
]
