export type GroupActivity = {
  id: string
  name: string
  category: "dances" | "mind-body" | "group-fitness"
  description: string
  image: string
  duration: string
  capacity: number
  instructor: string
  level: "beginner" | "intermediate" | "advanced" | "all-levels"
  schedule: string[]
}

export const GROUP_ACTIVITIES: GroupActivity[] = [
  // Dances (8 classes)
  {
    id: "zumba",
    name: "Zumba",
    category: "dances",
    description:
      "High-energy Latin-inspired dance workout that combines cardio and dance moves for a fun fitness experience",
    image: "/class-zumba.jpg",
    duration: "55 min",
    capacity: 30,
    instructor: "Maria Garcia",
    level: "all-levels",
    schedule: ["Mon 6:00 PM", "Wed 6:00 PM", "Fri 6:00 PM"],
  },
  {
    id: "hip-hop-dance",
    name: "Hip Hop Dance",
    category: "dances",
    description: "Learn urban dance moves and choreography in this high-energy hip hop class",
    image: "/class-hip-hop.jpg",
    duration: "60 min",
    capacity: 25,
    instructor: "Marcus Johnson",
    level: "intermediate",
    schedule: ["Tue 7:00 PM", "Thu 7:00 PM", "Sat 5:00 PM"],
  },
  {
    id: "salsa-dance",
    name: "Salsa Dance",
    category: "dances",
    description: "Master the passionate and rhythmic moves of salsa dancing in a social, energetic environment",
    image: "/class-salsa.jpg",
    duration: "60 min",
    capacity: 20,
    instructor: "Carlos Rivera",
    level: "beginner",
    schedule: ["Mon 7:30 PM", "Wed 7:30 PM"],
  },
  {
    id: "ballet-fitness",
    name: "Ballet Fitness",
    category: "dances",
    description: "Build strength, flexibility, and grace with ballet-inspired exercises at the barre",
    image: "/class-ballet.jpg",
    duration: "50 min",
    capacity: 15,
    instructor: "Sophie Laurent",
    level: "all-levels",
    schedule: ["Tue 9:00 AM", "Thu 9:00 AM", "Sat 10:00 AM"],
  },
  {
    id: "bollywood-dance",
    name: "Bollywood Dance",
    category: "dances",
    description: "Experience the vibrant and expressive dance style of Bollywood films",
    image: "/class-bollywood.jpg",
    duration: "55 min",
    capacity: 25,
    instructor: "Priya Sharma",
    level: "all-levels",
    schedule: ["Wed 6:30 PM", "Sat 4:00 PM"],
  },
  {
    id: "tap-dance",
    name: "Tap Dance",
    category: "dances",
    description: "Learn rhythm and coordination through the percussive art of tap dancing",
    image: "/class-tap.jpg",
    duration: "50 min",
    capacity: 18,
    instructor: "James Wilson",
    level: "beginner",
    schedule: ["Tue 5:00 PM", "Thu 5:00 PM"],
  },
  {
    id: "contemporary-dance",
    name: "Contemporary Dance",
    category: "dances",
    description: "Express yourself through fluid, interpretive movements that blend multiple dance styles",
    image: "/class-contemporary.jpg",
    duration: "60 min",
    capacity: 20,
    instructor: "Emma Chen",
    level: "intermediate",
    schedule: ["Mon 8:00 PM", "Fri 7:00 PM"],
  },
  {
    id: "line-dancing",
    name: "Line Dancing",
    category: "dances",
    description: "Join the fun with country-western line dancing perfect for all skill levels",
    image: "/class-line-dance.jpg",
    duration: "55 min",
    capacity: 30,
    instructor: "Bobby Hayes",
    level: "all-levels",
    schedule: ["Fri 6:00 PM", "Sun 3:00 PM"],
  },

  // Mind & Body (8 classes)
  {
    id: "hatha-yoga",
    name: "Hatha Yoga",
    category: "mind-body",
    description: "Traditional yoga practice focusing on breath control, flexibility, and mindful movement",
    image: "/class-hatha-yoga.jpg",
    duration: "60 min",
    capacity: 20,
    instructor: "Sarah Johnson",
    level: "all-levels",
    schedule: ["Mon 7:00 AM", "Wed 7:00 AM", "Fri 7:00 AM"],
  },
  {
    id: "vinyasa-flow",
    name: "Vinyasa Flow",
    category: "mind-body",
    description: "Dynamic yoga class linking breath with movement in flowing sequences",
    image: "/class-vinyasa.jpg",
    duration: "60 min",
    capacity: 25,
    instructor: "Maya Patel",
    level: "intermediate",
    schedule: ["Tue 6:00 PM", "Thu 6:00 PM", "Sat 9:00 AM"],
  },
  {
    id: "pilates-reformer",
    name: "Pilates Reformer",
    category: "mind-body",
    description: "Low-impact reformer workout targeting core strength and full-body conditioning",
    image: "/class-reformer.jpg",
    duration: "55 min",
    capacity: 12,
    instructor: "Lisa Anderson",
    level: "intermediate",
    schedule: ["Mon 8:00 AM", "Wed 12:00 PM", "Fri 8:00 AM"],
  },
  {
    id: "meditation-mindfulness",
    name: "Meditation & Mindfulness",
    category: "mind-body",
    description: "Guided meditation practice for stress reduction and mental clarity",
    image: "/class-meditation.jpg",
    duration: "30 min",
    capacity: 30,
    instructor: "Dr. Rachel Green",
    level: "all-levels",
    schedule: ["Mon 6:30 AM", "Wed 6:30 AM", "Fri 6:30 AM", "Sun 5:00 PM"],
  },
  {
    id: "tai-chi",
    name: "Tai Chi",
    category: "mind-body",
    description: "Ancient Chinese martial art emphasizing slow, flowing movements for balance and inner peace",
    image: "/class-tai-chi.jpg",
    duration: "45 min",
    capacity: 20,
    instructor: "Master Li Wei",
    level: "all-levels",
    schedule: ["Tue 7:00 AM", "Thu 7:00 AM", "Sat 8:00 AM"],
  },
  {
    id: "yin-yoga",
    name: "Yin Yoga",
    category: "mind-body",
    description: "Slow-paced yoga with longer-held poses for deep stretching and relaxation",
    image: "/class-yin-yoga.jpg",
    duration: "75 min",
    capacity: 18,
    instructor: "Jennifer Lee",
    level: "all-levels",
    schedule: ["Wed 8:00 PM", "Sun 4:00 PM"],
  },
  {
    id: "barre",
    name: "Barre",
    category: "mind-body",
    description: "Ballet-inspired workout combining elements of pilates, dance, and functional training",
    image: "/class-barre.jpg",
    duration: "50 min",
    capacity: 15,
    instructor: "Sophie Laurent",
    level: "all-levels",
    schedule: ["Mon 9:00 AM", "Wed 5:30 PM", "Sat 11:00 AM"],
  },
  {
    id: "breathwork",
    name: "Breathwork",
    category: "mind-body",
    description: "Explore various breathing techniques for energy, relaxation, and emotional release",
    image: "/class-breathwork.jpg",
    duration: "45 min",
    capacity: 25,
    instructor: "David Martinez",
    level: "all-levels",
    schedule: ["Tue 12:00 PM", "Thu 12:00 PM"],
  },

  // Group Fitness (8 classes)
  {
    id: "hiit-training",
    name: "HIIT Training",
    category: "group-fitness",
    description: "High-intensity interval training for maximum calorie burn and cardiovascular fitness",
    image: "/class-hiit.jpg",
    duration: "45 min",
    capacity: 20,
    instructor: "Mike Rodriguez",
    level: "intermediate",
    schedule: ["Mon 6:00 AM", "Wed 6:00 AM", "Fri 6:00 AM", "Sat 7:00 AM"],
  },
  {
    id: "spin-class",
    name: "Spin Class",
    category: "group-fitness",
    description: "Indoor cycling class with varying intensity for endurance and leg strength",
    image: "/class-spin.jpg",
    duration: "50 min",
    capacity: 25,
    instructor: "Emily Chen",
    level: "all-levels",
    schedule: ["Mon 5:30 AM", "Tue 5:30 PM", "Thu 5:30 PM", "Sat 8:00 AM"],
  },
  {
    id: "boxing-cardio",
    name: "Boxing Cardio",
    category: "group-fitness",
    description: "High-energy boxing workout combining technique with cardio conditioning",
    image: "/class-boxing.jpg",
    duration: "50 min",
    capacity: 18,
    instructor: "Alex Martinez",
    level: "all-levels",
    schedule: ["Tue 6:00 PM", "Thu 6:00 PM", "Sat 10:00 AM"],
  },
  {
    id: "boot-camp",
    name: "Boot Camp",
    category: "group-fitness",
    description: "Military-style workout combining strength training and cardio drills",
    image: "/class-bootcamp.jpg",
    duration: "55 min",
    capacity: 20,
    instructor: "Jake Thompson",
    level: "advanced",
    schedule: ["Mon 5:00 PM", "Wed 5:00 PM", "Fri 5:00 PM"],
  },
  {
    id: "step-aerobics",
    name: "Step Aerobics",
    category: "group-fitness",
    description: "Classic cardio workout using an adjustable step platform",
    image: "/class-step.jpg",
    duration: "50 min",
    capacity: 22,
    instructor: "Kelly Brown",
    level: "intermediate",
    schedule: ["Tue 9:00 AM", "Thu 9:00 AM", "Sat 9:00 AM"],
  },
  {
    id: "crossfit-fundamentals",
    name: "CrossFit Fundamentals",
    category: "group-fitness",
    description: "Learn proper form for functional fitness movements in a supportive group setting",
    image: "/class-crossfit.jpg",
    duration: "60 min",
    capacity: 15,
    instructor: "Coach Ryan",
    level: "beginner",
    schedule: ["Mon 7:00 PM", "Wed 7:00 PM"],
  },
  {
    id: "circuit-training",
    name: "Circuit Training",
    category: "group-fitness",
    description: "Rotate through stations of strength and cardio exercises for a full-body workout",
    image: "/class-circuit.jpg",
    duration: "50 min",
    capacity: 20,
    instructor: "Tom Harris",
    level: "all-levels",
    schedule: ["Tue 7:00 AM", "Thu 7:00 AM", "Sat 11:00 AM"],
  },
  {
    id: "aqua-fitness",
    name: "Aqua Fitness",
    category: "group-fitness",
    description: "Low-impact water-based workout perfect for all fitness levels and joint health",
    image: "/class-aqua.jpg",
    duration: "45 min",
    capacity: 18,
    instructor: "Nicole Stevens",
    level: "all-levels",
    schedule: ["Mon 10:00 AM", "Wed 10:00 AM", "Fri 10:00 AM"],
  },
]

export const CATEGORIES = [
  {
    id: "dances",
    name: "Dances",
    description: "Express yourself through movement with our diverse dance classes",
  },
  {
    id: "mind-body",
    name: "Mind & Body",
    description: "Find balance and peace with yoga, pilates, and mindfulness practices",
  },
  {
    id: "group-fitness",
    name: "Group Fitness",
    description: "High-energy group workouts for strength, cardio, and community",
  },
] as const
