"use client";

import { generateAIDietPlan } from "@/app/actions/gym";
import {
	Accordion,
	AccordionContent,
	AccordionItem,
	AccordionTrigger,
} from "@/src/components/ui/accordion";
import { Badge } from "@/src/components/ui/badge";
import { Button } from "@/src/components/ui/button";
import { Checkbox } from "@/src/components/ui/checkbox";
import {
	Field,
	FieldError,
	FieldGroup,
	FieldLabel,
	FieldLegend,
	FieldSet,
} from "@/src/components/ui/field";
import {
	Form,
	FormControl,
	FormDescription,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/src/components/ui/form";
import { Input } from "@/src/components/ui/input";
import { Separator } from "@/src/components/ui/separator";
import { DietRequest, DietRequestSchema } from "@/src/lib/types/actions";
import { DietPlan } from "@/src/lib/types/diet";
import { zodResolver } from "@hookform/resolvers/zod";
import { Brain, Loader2 } from "lucide-react";
import { useState } from "react";
import { Controller, useForm } from "react-hook-form";
import { toast } from "sonner";

const allergyOptions = ["Dairy", "Gluten", "Nuts", "Soy", "Eggs", "Shellfish"];

export default function AIDietPlansPage() {
	const [loading, setLoading] = useState(false);
	const [dietPlan, setDietPlan] = useState<DietPlan | null>(null);

	const form = useForm<DietRequest>({
		resolver: zodResolver(DietRequestSchema),
		defaultValues: {
			goal: "",
			height: "",
			weight: "",
			allergies: [],
		},
	});

	async function handleGenerate(requestParams: DietRequest) {
		setLoading(true);
		try {
			const result = await generateAIDietPlan(requestParams);
			
			setDietPlan(result);
		} catch (error) {
			console.error("Error generating workout:", error);
			toast("Failed to generate diet plan. Please try again.");
		} finally {
			setLoading(false);
		}
	}

	return (
		<>
			<div className="mx-auto max-w-4xl px-4 py-12">
				<div className="mb-12 text-center">
					<div className="flex items-center justify-center gap-2 mb-4">
						<Brain className="h-8 w-8 text-pink-500" />
						<h1 className="text-4xl font-bold">
							AI Diet Plan Generator
						</h1>
					</div>
					<p className="text-lg text-muted-foreground">
						Get a personalized meal plan generated by AI based on
						your goals and dietary restrictions
					</p>
				</div>

				<div className="rounded-lg border border-border p-8 mb-8">
					<div className="space-y-6">
						<Form {...form}>
							<form
								onSubmit={form.handleSubmit(handleGenerate)}
								className="space-y-8"
							>
								<FormField
									control={form.control}
									name="goal"
									render={({ field }) => (
										<FormItem>
											<FormLabel>
												Nutrition Goal
											</FormLabel>
											<FormControl>
												<Input
													placeholder="e.g., Muscle gain, Fat loss, Maintenance"
													className="mt-2"
													{...field}
												/>
											</FormControl>
											<FormDescription>
												This is your public display
												name.
											</FormDescription>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="height"
									render={({ field }) => (
										<FormItem>
											<FormLabel>
												Current Height
											</FormLabel>
											<FormControl>
												<Input
													placeholder="e.g., 175cm or 5'10''"
													className="mt-2"
													{...field}
												/>
											</FormControl>
											<FormDescription>
												This is your public display
												name.
											</FormDescription>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="weight"
									render={({ field }) => (
										<FormItem>
											<FormLabel>
												Current Weight
											</FormLabel>
											<FormControl>
												<Input
													placeholder="e.g., 75kg or 165lbs"
													className="mt-2"
													{...field}
												/>
											</FormControl>
											<FormDescription>
												This is your public display
												name.
											</FormDescription>
											<FormMessage />
										</FormItem>
									)}
								/>
								<Controller
									name="allergies"
									control={form.control}
									render={({ field, fieldState }) => (
										<FieldSet>
											<FieldLegend variant="label">
												Allergies
											</FieldLegend>
											<FieldGroup data-slot="checkbox-group">
												{allergyOptions.map(
													(allergy, idx) => (
														<Field
															key={idx}
															orientation="horizontal"
															data-invalid={
																fieldState.invalid
															}
														>
															<Checkbox
																id={`form-rhf-checkbox-${idx}`}
																name={
																	field.name
																}
																aria-invalid={
																	fieldState.invalid
																}
																checked={field.value.includes(
																	idx.toString()
																)}
																onCheckedChange={(
																	checked
																) => {
																	const newValue =
																		checked
																			? [
																					...field.value,
																					idx.toString(),
																			  ]
																			: field.value.filter(
																					(
																						value
																					) =>
																						value !==
																						idx.toString()
																			  );
																	field.onChange(
																		newValue
																	);
																}}
															/>
															<FieldLabel
																htmlFor={`form-rhf-checkbox-${idx}`}
																className="font-normal"
															>
																{allergy}
															</FieldLabel>
														</Field>
													)
												)}
											</FieldGroup>
											{fieldState.invalid && (
												<FieldError
													errors={[fieldState.error]}
												/>
											)}
										</FieldSet>
									)}
								/>
								<Button type="submit">
									{" "}
									{loading ? (
										<>
											<Loader2 className="mr-2 h-4 w-4 animate-spin" />
											Generating...
										</>
									) : (
										<>
											<Brain className="mr-2 h-4 w-4" />
											Generate Diet Plan
										</>
									)}
								</Button>
							</form>
						</Form>
					</div>
				</div>

				{dietPlan && (
					<div className="rounded-lg border border-border p-8">
						<div className="mb-6">
							<h2 className="text-2xl font-semibold mb-2">
								{dietPlan.name}
							</h2>
							<p className="text-muted-foreground mb-4">
								{dietPlan.description}
							</p>
							<div className="flex flex-wrap gap-2">
								<Badge variant="secondary">
									{dietPlan.calories}
								</Badge>
								<Badge variant="outline">
									Protein: {dietPlan.protein}
								</Badge>
								<Badge variant="outline">
									Carbs: {dietPlan.carbs}
								</Badge>
								<Badge variant="outline">
									Fats: {dietPlan.fats}
								</Badge>
							</div>
						</div>

						<div className="border-t border-border pt-6">
							<h3 className="font-semibold mb-4">
								Daily Meal Plan
							</h3>
							<div className="grid gap-3">
								{dietPlan.days.map(
									(
										day: DietPlan["days"][number],
										idx: number
									) => (
										<div
											key={`day-${idx}`}
											className="p-3 rounded-lg bg-muted"
										>
											<div className="flex items-center justify-between mb-1">
												<span className="font-medium">
													{day.name}
												</span>
												<Accordion
													type="single"
													collapsible
													className="w-full"
													defaultValue={`d-1-meal-0`}
												>
													{day.meals.map(
														(
															meal: DietPlan["days"][number]["meals"][number],
															mealIdx: number
														) => (
															<>
																<AccordionItem
																	value={`d-${idx}-meal-${mealIdx}`}
																>
																	<AccordionTrigger>
																		{
																			meal.name
																		}
																	</AccordionTrigger>
																	<AccordionContent className="flex flex-col gap-4 text-balance">
																		<p>
																			{
																				meal.amount
																			}
																		</p>
																		<p>
																			{
																				meal.recipe
																			}
																		</p>
																	</AccordionContent>
																</AccordionItem>
																<Separator className="my-4 w-0.5 bg-accent-foreground" />
															</>
														)
													)}
												</Accordion>
											</div>
										</div>
									)
								)}
							</div>
						</div>
					</div>
				)}
			</div>
		</>
	);
}
