"use client";

import { Navbar } from "@/src/components/navbar";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import { Label } from "@/src/components/ui/label";
import { generateAIDietPlan } from "@/app/actions/gym";
import { useState } from "react";
import { Loader2, Brain } from "lucide-react";
import { Badge } from "@/src/components/ui/badge";
import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import { Checkbox } from "@/src/components/ui/checkbox";

export default function AIDietPlansPage() {
	const { isSignedIn } = useAuth();
	const router = useRouter();
	const [goal, setGoal] = useState("");
	const [weight, setWeight] = useState("");
	const [allergies, setAllergies] = useState<string[]>([]);
	const [loading, setLoading] = useState(false);
	const [dietPlan, setDietPlan] = useState<any>(null);

	const allergyOptions = [
		"Dairy",
		"Gluten",
		"Nuts",
		"Soy",
		"Eggs",
		"Shellfish",
		"None",
	];

	const handleGenerate = async () => {
		if (!isSignedIn) {
			router.push("/sign-in");
			return;
		}

		if (!goal || !weight) {
			alert("Please fill in all fields");
			return;
		}

		setLoading(true);
		try {
			const result = await generateAIDietPlan({
				goal,
				weight,
				allergies,
			});
			setDietPlan(result);
		} catch (error) {
			console.error("Error generating diet plan:", error);
			alert("Failed to generate diet plan. Please try again.");
		} finally {
			setLoading(false);
		}
	};

	return (
		<>
			<Navbar />
			<main className="min-h-screen bg-background">
				<div className="mx-auto max-w-4xl px-4 py-12">
					<div className="mb-12 text-center">
						<div className="flex items-center justify-center gap-2 mb-4">
							<Brain className="h-8 w-8 text-pink-500" />
							<h1 className="text-4xl font-bold">
								AI Diet Plan Generator
							</h1>
						</div>
						<p className="text-lg text-muted-foreground">
							Get a personalized meal plan generated by AI based
							on your goals and dietary restrictions
						</p>
					</div>

					<div className="rounded-lg border border-border p-8 mb-8">
						<div className="space-y-6">
							<div>
								<Label htmlFor="goal">Nutrition Goal</Label>
								<Input
									id="goal"
									placeholder="e.g., Muscle gain, Fat loss, Maintenance"
									value={goal}
									onChange={(e) => setGoal(e.target.value)}
									className="mt-2"
								/>
							</div>

							<div>
								<Label htmlFor="weight">Current Weight</Label>
								<Input
									id="weight"
									placeholder="e.g., 75kg or 165lbs"
									value={weight}
									onChange={(e) => setWeight(e.target.value)}
									className="mt-2"
								/>
							</div>

							<div>
								<Label className="mb-3 block">
									Allergies & Restrictions
								</Label>
								<div className="grid gap-3 md:grid-cols-2">
									{allergyOptions.map((item) => (
										<div
											key={item}
											className="flex items-center space-x-2"
										>
											<Checkbox
												id={item}
												checked={allergies.includes(
													item
												)}
												onCheckedChange={(checked) => {
													if (checked) {
														setAllergies([
															...allergies,
															item,
														]);
													} else {
														setAllergies(
															allergies.filter(
																(a) =>
																	a !== item
															)
														);
													}
												}}
											/>
											<label
												htmlFor={item}
												className="text-sm cursor-pointer"
											>
												{item}
											</label>
										</div>
									))}
								</div>
							</div>

							<Button
								onClick={handleGenerate}
								disabled={loading}
								className="w-full"
								size="lg"
							>
								{loading ? (
									<>
										<Loader2 className="mr-2 h-4 w-4 animate-spin" />
										Generating...
									</>
								) : (
									<>
										<Brain className="mr-2 h-4 w-4" />
										Generate Diet Plan
									</>
								)}
							</Button>
						</div>
					</div>

					{dietPlan && (
						<div className="rounded-lg border border-border p-8">
							<div className="mb-6">
								<h2 className="text-2xl font-semibold mb-2">
									{dietPlan.name}
								</h2>
								<p className="text-muted-foreground mb-4">
									{dietPlan.description}
								</p>
								<div className="flex flex-wrap gap-2">
									<Badge variant="secondary">
										{dietPlan.calories}
									</Badge>
									<Badge variant="outline">
										Protein: {dietPlan.protein}
									</Badge>
									<Badge variant="outline">
										Carbs: {dietPlan.carbs}
									</Badge>
									<Badge variant="outline">
										Fats: {dietPlan.fats}
									</Badge>
								</div>
							</div>

							<div className="border-t border-border pt-6">
								<h3 className="font-semibold mb-4">
									Daily Meal Plan
								</h3>
								<div className="grid gap-3">
									{dietPlan.meals.map(
										(meal: any, idx: number) => (
											<div
												key={idx}
												className="p-3 rounded-lg bg-muted"
											>
												<div className="flex items-center justify-between mb-1">
													<span className="font-medium">
														{meal.name}
													</span>
													<span className="text-sm text-muted-foreground">
														{meal.time}
													</span>
												</div>
												<p className="text-sm text-muted-foreground">
													{meal.description}
												</p>
											</div>
										)
									)}
								</div>
							</div>
						</div>
					)}
				</div>
			</main>
		</>
	);
}
