"use client";

import { Navbar } from "@/src/components/navbar";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import { Label } from "@/src/components/ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/src/components/ui/select";
import { Checkbox } from "@/src/components/ui/checkbox";
import { generateAIWorkout } from "@/app/actions/gym";
import { useState } from "react";
import { Loader2, Sparkles } from "lucide-react";
import { Badge } from "@/src/components/ui/badge";
import { useAuth } from "@clerk/nextjs";
import { useRouter } from "next/navigation";

export default function AIWorkoutsPage() {
	const { isSignedIn } = useAuth();
	const router = useRouter();
	const [goal, setGoal] = useState("");
	const [level, setLevel] = useState("");
	const [equipment, setEquipment] = useState<string[]>([]);
	const [loading, setLoading] = useState(false);
	const [workout, setWorkout] = useState<any>(null);

	const equipmentOptions = [
		"Dumbbells",
		"Barbell",
		"Resistance Bands",
		"Kettlebells",
		"Pull-up Bar",
		"Bench",
		"Bodyweight Only",
	];

	const handleGenerate = async () => {
		if (!isSignedIn) {
			router.push("/sign-in");
			return;
		}

		if (!goal || !level || equipment.length === 0) {
			alert("Please fill in all fields");
			return;
		}

		setLoading(true);
		try {
			const result = await generateAIWorkout({ goal, level, equipment });
			setWorkout(result);
		} catch (error) {
			console.error("Error generating workout:", error);
			alert("Failed to generate workout. Please try again.");
		} finally {
			setLoading(false);
		}
	};

	return (
		<>
			<Navbar />
			<main className="min-h-screen bg-background">
				<div className="mx-auto max-w-4xl px-4 py-12">
					<div className="mb-12 text-center">
						<div className="flex items-center justify-center gap-2 mb-4">
							<Sparkles className="h-8 w-8 text-purple-500" />
							<h1 className="text-4xl font-bold">
								AI Workout Generator
							</h1>
						</div>
						<p className="text-lg text-muted-foreground">
							Get a personalized workout plan generated by AI
							based on your goals and available equipment
						</p>
					</div>

					<div className="rounded-lg border border-border p-8 mb-8">
						<div className="space-y-6">
							<div>
								<Label htmlFor="goal">Fitness Goal</Label>
								<Input
									id="goal"
									placeholder="e.g., Build muscle, Lose fat, Improve endurance"
									value={goal}
									onChange={(e) => setGoal(e.target.value)}
									className="mt-2"
								/>
							</div>

							<div>
								<Label htmlFor="level">Experience Level</Label>
								<Select value={level} onValueChange={setLevel}>
									<SelectTrigger className="mt-2">
										<SelectValue placeholder="Select your level" />
									</SelectTrigger>
									<SelectContent>
										<SelectItem value="beginner">
											Beginner
										</SelectItem>
										<SelectItem value="intermediate">
											Intermediate
										</SelectItem>
										<SelectItem value="advanced">
											Advanced
										</SelectItem>
									</SelectContent>
								</Select>
							</div>

							<div>
								<Label className="mb-3 block">
									Available Equipment
								</Label>
								<div className="grid gap-3 md:grid-cols-2">
									{equipmentOptions.map((item) => (
										<div
											key={item}
											className="flex items-center space-x-2"
										>
											<Checkbox
												id={item}
												checked={equipment.includes(
													item
												)}
												onCheckedChange={(checked) => {
													if (checked) {
														setEquipment([
															...equipment,
															item,
														]);
													} else {
														setEquipment(
															equipment.filter(
																(e) =>
																	e !== item
															)
														);
													}
												}}
											/>
											<label
												htmlFor={item}
												className="text-sm cursor-pointer"
											>
												{item}
											</label>
										</div>
									))}
								</div>
							</div>

							<Button
								onClick={handleGenerate}
								disabled={loading}
								className="w-full"
								size="lg"
							>
								{loading ? (
									<>
										<Loader2 className="mr-2 h-4 w-4 animate-spin" />
										Generating...
									</>
								) : (
									<>
										<Sparkles className="mr-2 h-4 w-4" />
										Generate Workout
									</>
								)}
							</Button>
						</div>
					</div>

					{workout && (
						<div className="rounded-lg border border-border p-8">
							<div className="mb-6">
								<h2 className="text-2xl font-semibold mb-2">
									{workout.name}
								</h2>
								<p className="text-muted-foreground mb-3">
									{workout.description}
								</p>
								<div className="flex items-center gap-3">
									<Badge>{workout.difficulty}</Badge>
									<span className="text-sm text-muted-foreground">
										{workout.duration}
									</span>
								</div>
							</div>

							<div className="border-t border-border pt-6">
								<h3 className="font-semibold mb-4">
									Exercise Plan
								</h3>
								<div className="grid gap-3">
									{workout.exercises.map(
										(exercise: any, idx: number) => (
											<div
												key={idx}
												className="flex items-center justify-between p-3 rounded-lg bg-muted"
											>
												<span className="font-medium">
													{exercise.name}
												</span>
												<span className="text-sm text-muted-foreground">
													{exercise.sets} sets ×{" "}
													{exercise.reps}{" "}
													{exercise.rest &&
														`• ${exercise.rest} rest`}
												</span>
											</div>
										)
									)}
								</div>
							</div>
						</div>
					)}
				</div>
			</main>
		</>
	);
}
